import { NextResponse } from "next/server"
import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { google } from "googleapis"
import fs from "fs"
import path from "path"


export const runtime = "nodejs" // ✅ VERY IMPORTANT

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url)

    const employee = searchParams.get("employee") || "All Employees"
    const from = searchParams.get("from") || "N/A"
    const to = searchParams.get("to") || "N/A"
    const type = searchParams.get("type") || "all"

    const sheetId = process.env.GOOGLE_SHEET_ID!

    // ✅ Google Auth
    const auth = new google.auth.JWT({
      email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
      scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
    })

    const sheets = google.sheets({ version: "v4", auth })

    // ✅ Read Sheet Data
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: sheetId,
      range: "Activities!A:I",
    })

    const rows = response.data.values || []
    const data = rows.slice(1)

    const start = new Date(from)
    const end = new Date(to)

    start.setHours(0, 0, 0, 0)
    end.setHours(23, 59, 59, 999)

    // ✅ Filter Data
    const filtered = data.filter((row) => {
      const name = row[2]
      const status = row[7]
      const blocker = row[8]

      const rawDate = row[5]
      if (!rawDate) return false

      const rowDate = new Date(rawDate)
      rowDate.setHours(0, 0, 0, 0)

      if (employee !== "All Employees" && name !== employee) return false

      if (rowDate < start || rowDate > end) return false

      if (type === "pending" && status !== "pending") return false
      if (type === "completed" && status !== "completed") return false
      if (type === "blocker" && blocker !== "TRUE") return false

      return true
    })

    // ✅ Create PDF
    const doc = new jsPDF()

    const logoPath = path.join(process.cwd(), "public", "company_logo.jpeg")
    const imageBuffer = fs.readFileSync(logoPath)
    const logoBase64 = `data:image/png;base64,${imageBuffer.toString("base64")}`

    // === Table Data
    const tableBody = filtered.slice(0, 15).map((row) => [
       row[2], // Name
      row[5], // Date
      row[3], // Type
      row[4], // Description
      row[6] + " min", // Duration
      row[7], // Status
    ])

    autoTable(doc, {
      head: [["Name", "Date", "Type", "Description", "Duration", "Status"]],
      body: tableBody,
      margin: { top: 80, bottom: 25 },
      styles: { fontSize: 9 },

      didDrawPage: () => {
        const pageWidth = doc.internal.pageSize.getWidth()
        const pageHeight = doc.internal.pageSize.getHeight()
        const margin = 8

        // ===== LOGO =====
        if (logoBase64) {
          doc.addImage(logoBase64, "PNG", pageWidth - margin - 50, 5, 50, 25)
        }
        const logoTop = 5
        const logoHeight = 25
        const headerBottom = logoTop + logoHeight + 5

        doc.setDrawColor(200) // light grey line
        doc.setLineWidth(0.7)
        doc.line(margin, headerBottom, pageWidth - margin, headerBottom)


        // ===== HEADER TEXT =====
        doc.setFontSize(16)

        // 🔹 Center - Activity Report
        doc.text("Activity Report", pageWidth / 2, headerBottom+10, {
          align: "center",
        })

        doc.setFontSize(11)

        // 🔹 Left - Employee
        doc.text(`Employee: ${employee}`, margin, headerBottom+20)

        // 🔹 Left - Type
        doc.text(`Type: ${type.toUpperCase()}`, margin, headerBottom+28)

        // 🔹 Right - From / To
        doc.text(`From: ${from}  To: ${to}`, pageWidth - margin, headerBottom+20, {
          align: "right",
        })

        

        // ===== FOOTER =====
        doc.setFontSize(9)

        doc.text(
          "Generated by Team Activity Logger System",
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        )

        const pageNumber = doc.internal.getCurrentPageInfo().pageNumber

        doc.text( 
          `Page ${pageNumber}`,
          pageWidth - margin,
          pageHeight - 10,
          { align: "right" }
        )
      }
    })




    // ✅ Convert PDF to Buffer
    const pdfBuffer = doc.output("arraybuffer")

    return new NextResponse(Buffer.from(pdfBuffer), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          'attachment; filename="Activity_Report.pdf"',
      },
    })
  } catch (err) {
    console.error("PDF Export Error:", err)

    return NextResponse.json(
      { error: "Failed to generate PDF" },
      { status: 500 }
    )
  }
}
